<a href="https://colab.research.google.com/github/Nishat-Tasnim-33/Algorithm/blob/main/tensorflow_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Creating tensorswith tf.constant()
scalar =tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [ ]:

# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# creating a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#checking the dimensionof our vector
vector.ndim

1

In [ ]:
from numpy.matrixlib.defmatrix import matrix
# Create a matrix (more than 1 dimension)
matrix = tf.constant([[10,20],
                      [20,30]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [20, 30]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:

# Create another matrix and define the datatype
another_matrix = tf.constant([[10.,20.],
                            [30.,40.],
                            [50.,60.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10., 20.],
       [30., 40.],
       [50., 60.]], dtype=float16)>

In [ ]:
# Even though another_matrix contains more numbers, its dimensions stay the same
another_matrix.ndim


2

In [ ]:

# How about a tensor? (more than 2 dimensions, although, all of the above items are also technically tensors
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                     [[13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3